#!/usr/bin/env python3
"""Generate CLAUDE.md from AGENTS.md (+ optional .agents/claude-overrides.md).

AGENTS.md is the source of truth — it follows the cross-tool AGENTS.md standard
(https://github.com/openai/codex), making the repo compatible with Codex CLI,
Cursor, Windsurf, Aider, etc. CLAUDE.md is the Claude Code-specific bridge —
it is generated by concatenating AGENTS.md with claude-overrides.md.

Modes:
  --write    : (default) write the generated content to CLAUDE.md
  --stdout   : print the generated content to stdout, do not touch CLAUDE.md
  --check    : compare existing CLAUDE.md against the generated content;
               exit 1 (with a diff) if they differ. Used by pre-commit.

Exit codes:
  0  success
  1  drift detected in --check mode, or sync target unwritable
  2  source file missing (AGENTS.md not found)
"""
from __future__ import annotations

import argparse
import difflib
import sys
from pathlib import Path

PROJECT_DIR = Path(__file__).resolve().parents[1]
AGENTS_MD = PROJECT_DIR / "AGENTS.md"
OVERRIDES_MD = PROJECT_DIR / ".agents" / "claude-overrides.md"
CLAUDE_MD = PROJECT_DIR / "CLAUDE.md"

HEADER = (
    "<!-- AUTO-GENERATED from AGENTS.md by scripts/sync_agents_md.py — DO NOT EDIT -->\n"
    "<!-- To change these rules edit AGENTS.md (universal) or .agents/claude-overrides.md (Claude-specific), then run: python scripts/sync_agents_md.py -->\n"
    "\n"
)


def _is_blank_or_comment(text: str) -> bool:
    """Return True when the overrides file has no user-visible content."""
    stripped = text.strip()
    if not stripped:
        return True
    # Treat a file that contains only HTML comments as effectively empty.
    in_comment = False
    for line in stripped.splitlines():
        line = line.strip()
        if not line:
            continue
        if in_comment:
            if "-->" in line:
                in_comment = False
            continue
        if line.startswith("<!--") and "-->" in line:
            continue
        if line.startswith("<!--"):
            in_comment = True
            continue
        return False
    return True


def generate() -> str:
    if not AGENTS_MD.exists():
        print(f"❌ Source not found: {AGENTS_MD}", file=sys.stderr)
        sys.exit(2)
    body = AGENTS_MD.read_text(encoding="utf-8").rstrip() + "\n"
    parts = [HEADER, body]
    if OVERRIDES_MD.exists():
        overrides = OVERRIDES_MD.read_text(encoding="utf-8")
        if not _is_blank_or_comment(overrides):
            parts.append("\n---\n\n## Claude Code-specific overrides\n\n")
            parts.append(overrides.rstrip() + "\n")
    return "".join(parts)


def cmd_write(content: str) -> int:
    CLAUDE_MD.write_text(content, encoding="utf-8", newline="\n")
    print(f"✅ Wrote {CLAUDE_MD.relative_to(PROJECT_DIR)} ({len(content)} bytes)")
    return 0


def cmd_stdout(content: str) -> int:
    sys.stdout.write(content)
    return 0


def cmd_check(content: str) -> int:
    if not CLAUDE_MD.exists():
        print("❌ CLAUDE.md missing — run `python scripts/sync_agents_md.py` to generate it.", file=sys.stderr)
        return 1
    current = CLAUDE_MD.read_text(encoding="utf-8")
    if current == content:
        return 0
    diff = difflib.unified_diff(
        current.splitlines(keepends=True),
        content.splitlines(keepends=True),
        fromfile="CLAUDE.md (current)",
        tofile="CLAUDE.md (expected from AGENTS.md)",
        n=2,
    )
    sys.stderr.write("❌ CLAUDE.md is out of sync with AGENTS.md.\n")
    sys.stderr.write("   Run: python scripts/sync_agents_md.py\n\n")
    sys.stderr.writelines(diff)
    return 1


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    group = parser.add_mutually_exclusive_group()
    group.add_argument("--write", action="store_true", help="write CLAUDE.md (default)")
    group.add_argument("--stdout", action="store_true", help="print to stdout")
    group.add_argument("--check", action="store_true", help="exit 1 if CLAUDE.md is stale")
    args = parser.parse_args()

    content = generate()
    if args.stdout:
        return cmd_stdout(content)
    if args.check:
        return cmd_check(content)
    return cmd_write(content)


if __name__ == "__main__":
    sys.exit(main())
